# Changes here will be overwritten by Copier
_commit: v0.2.3
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage code scanner
distribution_name: swh-scanner
have_cli: true
have_workers: false
package_root: swh/scanner
project_name: swh.scanner
python_minimal_version: '3.7'
readme_format: rst
